name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: Linux

    steps:
    - uses: actions/checkout@v3
    - name: pip install 
      run: pip install .

